name: CI
"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          cache: "pip"
          cache-dependency-path: "**/setup.cfg"
          python-version: "${{ matrix.python-version }}"
      - run: pip install -U pip setuptools wheel
      - run: "pip install -e .[test]"
      - run: py.test -vvv --cov .
      - uses: codecov/codecov-action@v2
  Lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          cache: "pip"
          cache-dependency-path: "**/setup.cfg"
          python-version: "3.10"
      - run: pip install -e .[dev]
      - run: black --check .
      - run: isort --check .
      - run: flake8 wattson
      - run: mypy wattson --strict --show-error-codes
  Build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          cache: "pip"
          cache-dependency-path: "**/setup.cfg"
          python-version: "3.10"
      - run: pip install -U pip setuptools build
      - run: python -m build .
