name: Publish
"on":
  push:
    tags:
      - "v*"
jobs:
  Publish:
    runs-on: ubuntu-20.04
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: actions/checkout@v2
      - run: pip install -U pip setuptools build twine
      - run: python -m build .
      - run: twine upload --verbose dist/*
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
